### ISSUE TITLE
[BUG] List of unsynced elements DA62

### ISSUE THREAD

**Issue by marccreal** [Sequal32/yourcontrols#30] opened 2020-11-09 15:13 UTC
![image](https://user-images.githubusercontent.com/63705372/98558723-0d6b8d80-22a6-11eb-8bc2-47134d70aa36.png)

- Elect Master
- Starter Left
- Starter Right

**Comment by marccreal** [comment] 2020-11-09 22:15
I had a look at the Simvars with the tool from the SDK:
- Elect Master:
ELECTRICAL MASTER BATTERY:1,Bool,  1
--> is already in the config file, so I'm not sure why it does not work.

- Starter Left/Right:
GENERAL ENG STARTER:1,Bool,  0
GENERAL ENG STARTER:2,Bool,  0
GENERAL ENG STARTER ACTIVE:1,Bool,  0
GENERAL ENG STARTER ACTIVE:2,Bool,  0
--> the first two are already in the config.  Note sure if the last two are needed/would fix the problem.

**Comment by Sequal32** [comment] 2020-11-10 01:58
Could not reproduce the starters not working, however the master battery had a duplicate entry causing it to turn off and back on again quickly, so addressed in 2360e10ed0651072ace29f6333f84280bd4ad4ac. Thanks!

**Closed** 2020-11-13 06:49 UTC
Labels: bug

**Comment by marccreal** [comment] 2020-11-17 14:25
I can confirm that the Master battery works now but the starters do not. As you cannot reproduce this, I'm not sure, where the problem is. Do you click and immediately release the button for starting or do you click and hold for a while?

**Comment by Sequal32** [comment] 2020-11-18 14:23
Should just work with a click, I'll do some more testing and try to figure out what's wrong
