### ISSUE TITLE
Feature request: Allow the host to take controls without permission.

### ISSUE THREAD

**Issue by Hugo22O** [Sequal32/yourcontrols#46] opened 2020-11-20 22:38 UTC
Hi!

This mod is amazing and I've had tons of fun with it. One feature I'm missing is that the host can take control back when someone else is in control without the person in control having to do that. 

Thank you!

**Comment by Sequal32** [comment] 2020-11-23 02:20
Thanks! This will be added soon, but duplicate of #31

**Closed by Sequal32** 2020-11-23 02:20 UTC
Labels: duplicate
