### ISSUE TITLE
[BUG] CTD while using mod at newest MSFS Version

### ISSUE THREAD

**Issue by Trigger81** [Sequal32/yourcontrols#107] opened 2021-04-19 10:02 UTC
CTD while using mod at newest MSFS Version

**To Reproduce**
1. Start MSFS with the mod
2. Get crash to desktop

**Comment by Sequal32** [comment] 2021-04-19 17:52
Duplicate of #104
Make sure you're on MSFS vresion 1.15.8.0.

**Closed by Sequal32** 2021-04-19 17:52 UTC
Labels: bug
