### ISSUE TITLE
List of unsynchronized buttons and dials - flybywire A32X

### ISSUE THREAD

**Issue by ToasterF16** [Sequal32/yourcontrols#29] opened 2020-11-08 12:11 UTC
Airbus version 0.4.1
yourcontrols version 2.2.0

Autobrake Buttons
BARO/REF Selector (does a weird wiggling back and forth, both users have to turn at the same time)
TAKE OFF CONFIG BUTTON

**Comment by TwitchyShell** [comment] 2020-11-09 06:25
Taxi light
Black guards on Cabin call EMER and RAM AIR open uncommanded upon connection

**Comment by markusa380** [comment] 2020-11-09 17:51
When the client connects, not only do a lot of switches automatically turn, also does the aircraft start ringing and all indicators light up (probably a self test of some sort) - but only for the server....

**Comment by Sequal32** [comment] 2020-11-10 01:56
@ToasterF16 autobrakes added in 61dfb95b17ec57154c4f6771319c387865a8bdf2, altimeter bug not reported in the version I'm testing with people, so should be addressed in next release... the takeoff config button is finicky since it uses a local variable that turns off immediately so there's not enough time to be read by the sim... not sure what can be done with this 

@TwitchyShell were you using the stable version of the A32NX? 100% sure all the light switches synced then, as well as the trim

@markusa380 will be addressed in the next release - needed an update of the gauge

**Comment by TwitchyShell** [comment] 2020-11-10 04:21
Stable A32NX v0.4.1, yourcontrols v2.2.0

Taxi light only, rest are working as intended.

Manual trim from master syncs to slave only (I understand that may be by design but causes minor problems with some SOPs where PNF adjusts TO trim)

**Comment by Sequal32** [comment] 2020-11-10 04:32
Alright I'll take a look into the taxi lights. Regarding the trim syncing for both... I guess I can disable trim syncing while autopilot is enabled, but allow both pilots to control it then.

**Comment by MrMinimal** [comment] 2020-11-14 14:43
Flight director (FD buttons) for both sides doesn't sync.

**Comment by Sequal32** [comment] 2020-11-14 22:22
Thanks! Fixed in cfe6d6ab82b5bb4d48ddccb663dec9bc93319a19

**Closed** 2020-11-25 02:35 UTC
Labels: bug
