### ISSUE TITLE
[BUG] Version 2.3.0 Simconnect issues

### ISSUE THREAD

**Issue by C0PAN** [Sequal32/yourcontrols#39] opened 2020-11-13 22:45 UTC
**Simconnnect Issues**
Your control do not connects to Simconnect, warning "Not connected".
Can't save settings, or start server or start as client, it becomes a blank page.

**How To Reproduce**

1. Just start YourControl app as recommended (only after flight are ready and exactly equal to your partner);
2. App starts;
3. Simconnect "Not connected" warning;
4. Push start server gives blank page, close it;
5. Restart app;
6. Trying to connect as client gives blank page, close it;
7. Restart app;
8. Trying to save any settings, gives blank page.

PS: No matter the procedures order.

*It's not working for me and my partner (FullerHKZ), same issues on both.

*Version 2.2.0 was working. I've tried to use it after 2.3.0 but it's not working anymore.

*LOG*
21:39:31 [INFO] Creating webview...
21:39:31 [INFO] Spawning webview thread...
21:39:31 [INFO] Connected to SimConnect.
21:39:31 [INFO] Running webview thread...
21:39:34 [INFO] Found 9 configuration file(s).
21:39:34 [INFO] Version 2.3.0 in use, 2.3.0 is newest.

**Comment by Sequal32** [comment] 2020-11-13 22:52
Hey I would love to solve this issue with you, if you have a discord can you join the server listed in the Readme? Ping me with once you're there.

**Comment by SafeShows** [comment] 2020-11-13 23:14
Also could you please tell us what Windows version your running and what build of Windows?

**Comment by C0PAN** [comment] 2020-11-13 23:38
> Also could you please tell us what Windows version your running and what build of Windows?
I'm using Windows 10 64 bits (Version 20H2)

**Comment by SafeShows** [comment] 2020-11-14 00:02
@Sequal32 this is the issue here
![image](https://user-images.githubusercontent.com/49234603/99132006-72fca880-261d-11eb-9726-3051319998c9.png)

**Comment by Sequal32** [comment] 2020-11-14 02:35
Was caused by error fetching from CDN. Fixed in e0e000405b029ef84dff082641b309b2486ceaaa

**Closed by Sequal32** 2020-11-14 02:35 UTC
Labels: bug
