### ISSUE TITLE
[BUG] msfs2p craschibg on start

### ISSUE THREAD

**Issue by mixsiak** [Sequal32/yourcontrols#105] opened 2021-04-18 18:16 UTC
**Describe the bug**

download and pug your control community into msfs20 Community folder.   

Loading msfs crash to desktop in loading screen
if I delete your control folder from community it will load up normally

**To Reproduce**
Steps to reproduce the behavior, for example: 
1. Start as server.
2. Transfer control to client
3. Flip the navigation lights.

**Expected behavior**
A clear and concise description of what you expected to happen. For example: Navigation lights are synced between all clients.

**Additional context**

**__PLEASE ATTACH EVERYONE'S LOGS__**
`Log.txt` can be found in the directory of the .exe file`

**Discord**
Your discord name if you're in the YourControl discord server.

**Comment by Sequal32** [comment] 2021-04-18 19:28
Duplicate of https://github.com/Sequal32/yourcontrols/issues/104
Make sure you're on MSFS vresion 1.15.8.0.

**Closed by Sequal32** 2021-04-18 19:28 UTC
Labels: bug
